language: node_js
git:
  depth: 3
node_js:
  - "6"

# --- CRITICAL FIX: Ensure Chrome for Headless Tests is installed ---
addons:
  chrome: stable # This tells Travis CI to install a stable version of Google Chrome

env:
  matrix:
    - TWBS_TEST=core
    - TWBS_TEST=validate-html
    - TWBS_TEST=browserstack
before_install:
  # --- FIX FOR RUBY/BUNDLER INCOMPATIBILITY
  - source /home/travis/.rvm/scripts/rvm || true 
  - rvm use 2.6.10 --install --default
  - gem install bundler -v 1.17.3 --no-document --no-user-install

  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip browserstack\]'; export TWBS_DO_BROWSERSTACK=$?; true
install:
  - bundle install --deployment --jobs=3 --retry=3 --clean
  - npm install
cache:
  directories:
    - node_modules
    - vendor/bundle

script:
  - npm run release
  - ls
deploy:
  provider: releases
  # api_key:
  #   secure: "$GITHUB_TOKEN" # Your encrypted GitHub PAT. Store securely in Travis CI settings.
  # file: bootstrap-dist-v${TRAVIS_TAG:-$(npm pkg get version | tr -d '"')}.zip # Matches the zip created by 'npm run release-zip'
  on: # <<< Add this 'on' block
    branch: main # Deploy on main branch commits
    tags: true   # Deploy on tags as well
  file: bootstrap-3.4.1-sp1-dist.zip
  skip_cleanup: true # Important: Prevents Travis from deleting the artifact before deployment
  name: "Build Artifacts ${{ TRAVIS_TAG }}" # Release name on GitHub
  body: "Automated build artifacts for tag ${{ TRAVIS_TAG }}" # Release description

notifications:
  email: false
